<a href="https://colab.research.google.com/github/jattFaizan423/Faizan-jatt/blob/main/Airbnb_Open_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [228]:
import numpy as np
import pandas as pd
import seaborn as sns

In [229]:
df1 = pd.read_csv('/content/Airbnb_Open_Data.csv')

/tmp/ipython-input-3999674294.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('/content/Airbnb_Open_Data.csv')

In [230]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [231]:
df = df1.copy()

In [280]:
df1.head(5)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,07/05/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [232]:
df['id'] = df['id'].astype(int)

In [233]:
df['host id'] = df['host id'].astype(int)

In [234]:
df['host_identity_verified'] = df['host_identity_verified'].fillna('unconfirmed').str.capitalize().astype('category')

In [235]:
df['host name'] = df['host name'].fillna('Michael').str.strip().str.capitalize().astype('category')

In [236]:
df['neighbourhood group'] = df['neighbourhood group'].fillna('Manhattan').str.strip().str.capitalize().astype('category')

In [237]:
df['neighbourhood'] = df['neighbourhood'].fillna('Bedford-Stuyvesant').str.strip().str.replace('-',' ').str.replace(',',' ').str.capitalize().astype('category')

In [238]:
df.rename(columns={'lat':'latitude','long':'longitude'},inplace=True)

In [239]:
df['latitude'] = df['latitude'].fillna('40.72').astype(float).round(2)

In [240]:
df['longitude'] = df['longitude'].fillna('-73.95').astype(float).round(2)

In [241]:
df['country'] = df['country'].fillna('United States').str.strip().str.capitalize().astype('category')

In [242]:
df['country code'] = df['country code'].fillna('US').str.strip().str.capitalize().astype('category')

In [243]:
df['instant_bookable'].fillna(df['instant_bookable'].mode()[0], inplace=True)
df['instant_bookable'] = df['instant_bookable'].astype('bool')

/tmp/ipython-input-2822073284.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['instant_bookable'].fillna(df['instant_bookable'].mode()[0], inplace=True)
/tmp/ipython-input-2822073284.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['instant_bookable'].fillna(df['instant_bookable'].mode()[0], inplace=True)

In [244]:
df['cancellation_policy'] = df['cancellation_policy'].fillna('flexible').str.strip().str.capitalize().astype('category')

In [245]:
df['room type'] = df['room type'].fillna('Entire home').str.strip().str.split('/').str[0].astype('category')

In [246]:
df['Construction year'] = df['Construction year'].fillna('2011.0').astype(float).astype('int32')

In [247]:
df['price'] = df['price'].fillna('$67').str.strip().str.replace('$','').str.replace(',','').astype('int32')

In [248]:
df['service fee'] = df['service fee'].fillna('$203').str.strip().str.replace('$','').astype('int32')

In [249]:
df['minimum nights'] = df['minimum nights'].fillna('2.0').astype(float).astype('int32')

In [250]:
df['number of reviews'] = df['number of reviews'].fillna('0.0').astype(float).astype('int32')

In [251]:
df['last review'] = df['last review'].fillna('2019-06-23')

In [273]:
df['last review'] = pd.to_datetime(df['last review'], errors='coerce')

In [252]:
df['reviews per month'] = df['reviews per month'].fillna('0.02').astype(float)

In [253]:
df['review rate number'] = df['review rate number'].fillna('5.0').astype(float)

In [254]:
df['calculated host listings count'] = df['calculated host listings count'].fillna('1.0').astype(float).astype('int32')

In [255]:
df['calculated host listings count'] = df['calculated host listings count'].astype('int32')

In [256]:
df['availability 365'] = df['availability 365'].fillna('197.0').astype(float).astype('int32')

In [257]:
df['availability 365'] = df['availability 365'].astype('int32')

In [266]:
df.rename(columns={
    'calculated host listings count': 'host_listings_count',
    'availability 365': 'days_available'
}, inplace=True)

In [270]:
df.drop(['NAME','license','house_rules'],axis=1,inplace=True)

In [281]:
df.head(9)

,id,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,latitude,longitude,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,host_listings_count,days_available
0,1001254,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.65,-73.97,United states,Us,False,Strict,Private room,2020,966,193,10,9,2021-10-19,0.21,4.0,6,286
1,1002102,52335172823,Verified,Jenna,Manhattan,Midtown,40.75,-73.98,United states,Us,False,Moderate,Entire home,2007,142,28,30,45,2022-05-21,0.38,4.0,2,228
2,1002403,78829239556,Unconfirmed,Elise,Manhattan,Harlem,40.81,-73.94,United states,Us,True,Flexible,Private room,2005,620,124,3,0,NaT,0.02,5.0,1,352
3,1002755,85098326012,Unconfirmed,Garry,Brooklyn,Clinton hill,40.69,-73.96,United states,Us,True,Moderate,Entire home,2005,368,74,30,270,2019-07-05,4.64,4.0,1,322
4,1003689,92037596077,Verified,Lyndon,Manhattan,East harlem,40.80,-73.94,United states,Us,False,Moderate,Entire home,2009,204,41,10,9,2018-11-19,0.10,3.0,1,289
5,1004098,45498551794,Verified,Michelle,Manhattan,Murray hill,40.75,-73.97,United states,Us,True,Flexible,Entire home,2013,577,115,3,74,2019-06-22,0.59,3.0,1,374
6,1004650,61300605564,Unconfirmed,Alberta,Brooklyn,Bedford stuyvesant,40.69,-73.96,United states,Us,False,Moderate,Private room,2015,71,14,45,49,2017-10-05,0.40,5.0,1,224
7,1005202,90821839709,Unconfirmed,Emma,Brooklyn,Bedford stuyvesant,40.69,-73.96,United states,Us,False,Moderate,Private room,2009,1060,212,45,49,2017-10-05,0.40,5.0,1,219
8,1005754,79384379533,Verified,Evelyn,Manhattan,Hell's kitchen,40.76,-73.98,United states,Us,True,Strict,Private room,2005,1018,204,2,430,2019-06-24,3.47,3.0,1,180

In [275]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 23 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      102599 non-null  int64
 1   host id                 102599 non-null  int64
 2   host_identity_verified  102599 non-null  category
 3   host name               102599 non-null  category
 4   neighbourhood group     102599 non-null  category
 5   neighbourhood           102599 non-null  category
 6   latitude                102599 non-null  float64
 7   longitude               102599 non-null  float64
 8   country                 102599 non-null  category
 9   country code            102599 non-null  category
 10  instant_bookable        102599 non-null  bool
 11  cancellation_policy     102599 non-null  category
 12  room type               102599 non-null  category
 13  Construction year       102599 non-null  int32
 14  price                   102599 non-null  int32
 15  service fee             102599 non-null  int32
 16  minimum nights          102599 non-null  int32
 17  number of reviews       102599 non-null  int32
 18  last review             86706 non-null   datetime64[ns]
 19  reviews per month       102599 non-null  float64
 20  review rate number      102599 non-null  float64
 21  host_listings_count     102599 non-null  int32
 22  days_available          102599 non-null  int32
dtypes: bool(1), category(8), datetime64[ns](1), float64(4), int32(7), int64(2)
memory usage: 9.9 MB